import './js/api.js';
import './js/categories.js';
import './js/filter.js';
import './js/btn-to-top.js';
import './js/modal_window_recipe.js';
import './js/slider.js';
import './js/order.js';
import './js/hendlers_filter.js';
import './js/gallery.js';
